In [1]:
import numpy as np
import pandas as pd
import PIL as Image

In [2]:
arr=np.array([1,2,3,6,4,5])
np.flip(arr)

array([5, 4, 6, 3, 2, 1])

In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
np.ndarray.flatten(array1)

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1,arr2)

True

In [5]:
np.allclose(arr1,arr2,atol=0.1)

True

In [6]:
np.setdiff1d(arr1,arr2)

array([], dtype=int64)

In [7]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(np.bincount(x).argmax())
values,counts=np.unique(x,return_counts=True)
maxi=values[np.argmax(counts)]
index=np.where(x==maxi)[0]
print(index)

1
[0 5 7 8 9]


In [8]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(np.bincount(y).argmax())
values,counts=np.unique(y,return_counts=True)
maxi=values[np.argmax(counts)]
index=np.where(y==maxi)[0]
print(index)

1
[0 1 2]


In [9]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))

45


In [10]:
print(np.sum(gfg,axis=0))

[[20  9 16]]


In [11]:
print(np.sum(gfg,axis=1))

[[14]
 [16]
 [15]]


In [12]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.trace(n_array))

176


In [13]:
eigval=np.linalg.eigvals(n_array)
print(eigval)

[98.16835147 28.097044   49.73460452]


In [14]:
eigenvalues,eigenvectors=np.linalg.eig(n_array)
print(eigenvalues)
print(eigenvectors)

[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [15]:
np.linalg.inv(n_array)

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [16]:
np.linalg.det(n_array)

np.float64(137180.0000000001)

In [17]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print(np.dot(p,q))
print(np.cov(p,q))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [18]:
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
print(np.dot(p,q))
combined = np.vstack((p.flatten(), q.flatten()))
print(np.cov(combined))

[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [19]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
np.inner(x,y)

array([[17, 52],
       [13, 62]])

In [20]:
np.outer(x,y)

array([[ 2, 10,  0, 10, 20,  6],
       [ 3, 15,  0, 15, 30,  9],
       [ 4, 20,  0, 20, 40, 12],
       [ 3, 15,  0, 15, 30,  9],
       [ 2, 10,  0, 10, 20,  6],
       [ 9, 45,  0, 45, 90, 27]])

In [21]:
np.cross(x,y)

array([[-20,   4,   7],
       [-84,  36,  20]])

In [22]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
np.abs(array)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr=array.flatten()

In [24]:
per=np.percentile(arr,[25,50,75])
per

array([-3.5, -0.5,  2.5])

In [25]:
per=np.percentile(array,[25,50,75],axis=0)
per

array([[-2.75, -0.25, -3.75],
       [-1.5 ,  1.5 , -1.5 ],
       [-0.25,  3.25,  0.75]])

In [26]:
perrow=np.percentile(array,[25,50,75],axis=1)
perrow

array([[-0.5, -5. ],
       [ 1. , -4. ],
       [ 2. ,  0.5]])

In [27]:
print(np.mean(arr))

-0.5


In [28]:
print(np.median(arr))

-0.5


In [29]:
print(np.std(arr))

3.8622100754188224


In [30]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  3.])

In [31]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [32]:
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  3.])

In [33]:
np.round(a)

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

In [34]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted=np.sort(array)
sorted

array([ 10,  16,  16,  52,  54,  62, 453])

In [35]:
np.argsort(array)

array([0, 3, 4, 1, 5, 2, 6])

In [36]:
sorted[:4]

array([10, 16, 16, 52])

In [37]:
np.flip(sorted[-5:])

array([453,  62,  54,  52,  16])

In [38]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer = array[np.isclose(array, np.round(array))]
integer

array([1., 2., 3., 2.])

In [39]:
floati = array[~np.isclose(array, np.round(array))]
floati

array([1.2, 2.2])

In [40]:

def img_to_array(path):
    image = Image.open(path)
    img_array = np.array(image)
    
    if len(img_array.shape) == 2:
        np.savetxt('grayscale_image.txt', img_array, fmt='%d')
        print("Grayscale image saved as grayscale_image.txt")
    elif len(img_array.shape) == 3 and img_array.shape[2] == 3:
        np.savetxt('rgb_image.txt', img_array.reshape(-1, 3), fmt='%d', delimiter=',')
        print("RGB image saved as rgb_image.txt")
    else:
        print("Unsupported image type")

In [41]:
df=np.random.rand(10,4)

In [42]:
dff=pd.DataFrame(df)

In [43]:
dff

0         1         2         3
0  0.034255  0.059210  0.799727  0.303948
1  0.061136  0.059624  0.417202  0.834916
2  0.923038  0.288880  0.593787  0.203017
3  0.868211  0.927639  0.623831  0.476110
4  0.281502  0.243078  0.611057  0.685254
5  0.558051  0.447038  0.080851  0.277839
6  0.957447  0.507516  0.230621  0.886417
7  0.158493  0.994147  0.752142  0.380118
8  0.565496  0.003397  0.192229  0.239812
9  0.602094  0.734734  0.171460  0.513562

In [44]:
dff.iloc[-6]

0    0.281502
1    0.243078
2    0.611057
3    0.685254
Name: 4, dtype: float64